### ISSUE TITLE
커뮤니티 개선사항

### ISSUE THREAD

**Issue by ByeongbumSeo** [HH-Final-Project-2/BackEnd#58]
## To-Do
- [x] 댓글 리스트 표시순서 역순으로(최신순) 배열해야 할 것 같습니다.
- [x] 글 작성 시, 필수 입력사항이 다 입력되지 않은 채로 작성을 누르면 페이지 오류, 뒤로가기도 안됨
- [x] 게시글 내용 입력란 늘리기, 제목 글자 수 제한
- [ ] 게시글 전체 조회 시 게시글 좋아요 클릭 기능 구현
