### ISSUE TITLE
개인일정 개선사항

### ISSUE THREAD

**Issue by yusung4612** [HH-Final-Project-2/BackEnd#59]
## To-Do
- [ ] 제목, 내용 중 하나라도 작성하지 않을 시 일정 미등록
- [ ] 일정 삭제 시 에러 메시지 변경 필요
- [ ] 일정 수정 페이지 필요
- [ ] 캘린더의 요일 순서와 일정 등록 시 날짜 선택하는 요일 순서 형식이 다름
- [ ] 당일 일정의 시간설정을 오전 9시 이전부터 이후로 설정하면 전날까지 일정이 등록이 되는 현상

**Comment by ByeongbumSeo** [comment]
추가로 ~~~ 오류 발견해서 추가해놨습니다

**Comment by ssssssg-hub** [comment]
일정삭제 에러메시지 변경
제목, 내용중 하나라도 작성하지 않으면 일정 미등록 -> 내용은 작성하지 않아도 되게 바꾸고 나머지 값들은 예외처리 완료
일정 작성시 시간설정 오전 9시 이전으로 설정하면 전날로 등록되는 현상 해결
개인일정 삭제버튼 수정
개인일정 상세조회 페이지 제작
완료했습니다

**Comment by kimbokyung1220** [comment]
> 일정삭제 에러메시지 변경 제목, 내용중 하나라도 작성하지 않으면 일정 미등록 -> 내용은 작성하지 않아도 되게 바꾸고 나머지 값들은 예외처리 완료 일정 작성시 시간설정 오전 9시 이전으로 설정하면 전날로 등록되는 현상 해결 개인일정 삭제버튼 수정 개인일정 상세조회 페이지 제작 완료했습니다

#50 캘린더 상세보기 기능 추가해 뒀습니다!
확인 부탁드립니다 감사합니다

**Comment by kimbokyung1220** [comment]
> https://github.com/HH-Final-Project-2/BackEnd/issues/59#issuecomment-1339971057

개인일정 상세조회 기능 구현완료 했습니다
확인부탁드리겠습니다 감사합니다!
@ssssssg-hub

**Comment by ssssssg-hub** [comment]
개인일정 상세조회 기능 확인 후 상세조회 페이지 구현했습니다

**Comment by ssssssg-hub** [comment]
캘린더의 요일 순서와 일정 등록 시 날짜 선택하는 요일 순서 형식이 다름 > 이건 찾아보았으나 datePicker와 react-calendar 형태가 달라서 발생하는 문제였고 datePicker쪽을 수정해서 맞추고 싶었으나 수정할 수 있는 방법이 없는 것으로 판단되어 내 일정 페이지에서 보이는 달력을 일월화수목금토 순으로 나열시켜서 형태를 맞췄습니다
@kimbokyung1220

**Comment by dyhwnag** [comment]
개인일정 작성 후 렌더링 이슈 해결 완료했습니다
