### ISSUE TITLE
내 명함 개선사항

### ISSUE THREAD

**Issue by yusung4612** [HH-Final-Project-2/BackEnd#70]
## To-Do
- [ ] 명함 업로드 시 리사이징 필요
- [ ] 회사 검색 불가
- [ ] 명함 업로드 후 이름칸과 영문 이름칸을 클릭시 null 글씨가 자동으로 출력 됨
- [ ] 내 명함 사진 삭제 후 재업로드 기능 필요
