### ISSUE TITLE
채팅기능 개선사항

### ISSUE THREAD

**Issue by ByeongbumSeo** [HH-Final-Project-2/BackEnd#72]
## To-Do
- [ ] 채팅방 목록 조회화면에서 실시간으로 unread 카운트 및 lastMessage 변하게 하기
- [ ] 채팅방에서 (읽음),(안읽음) 처리
- [ ] 채팅방이 여러개인 경우, 각각의 채팅방에 접속이 잘 되지 않음
- [ ] 프론트) 만약 채팅시간이 분단위까지 같다면 채팅박스를 붙이기 
- [ ] 채팅방 생성 시,  채팅이 시작되었습니다를 맨 위에 표시해주기

**Comment by ByeongbumSeo** [comment]
> 채팅방이 여러개인 경우, 각각의 채팅방에 접속이 잘 되지 않음
이 부분에 대해서 방금 캐치했습니다. 최대한 빠른 시일내에 fix하겠습니다. @andamiro98
